{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Product defects",
    "children" : [ {
      "name" : "web3_eth_contract_1.Contract is not a constructor",
      "children" : [ {
        "name" : "simple contract deployment",
        "uid" : "105c79a167c9def5",
        "parentUid" : "95946c1fb683d8dfc7058534e9f1029b",
        "status" : "failed",
        "time" : {
          "start" : 1632557290787,
          "stop" : 1632557292255,
          "duration" : 1468
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "1_Storage.sol" ]
      }, {
        "name" : "simple contract deployment",
        "uid" : "9336651651c7d2e7",
        "parentUid" : "95946c1fb683d8dfc7058534e9f1029b",
        "status" : "failed",
        "time" : {
          "start" : 1632557292256,
          "stop" : 1632557293372,
          "duration" : 1116
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "3_Ballot.sol" ]
      }, {
        "name" : "simple contract deployment",
        "uid" : "5e6a99e82276913d",
        "parentUid" : "95946c1fb683d8dfc7058534e9f1029b",
        "status" : "failed",
        "time" : {
          "start" : 1632557293373,
          "stop" : 1632557293746,
          "duration" : 373
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "proof.sol" ]
      } ],
      "uid" : "95946c1fb683d8dfc7058534e9f1029b"
    }, {
      "name" : "Returned error: HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3a7b48070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "a user to user successful transaction",
        "uid" : "22570b32be445065",
        "parentUid" : "d725c2a9f1b7aa4eb91b119ae2328283",
        "status" : "failed",
        "time" : {
          "start" : 1632557293747,
          "stop" : 1632557294568,
          "duration" : 821
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ "1", "10" ]
      } ],
      "uid" : "d725c2a9f1b7aa4eb91b119ae2328283"
    }, {
      "name" : "Returned error: HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3ac082550>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "a user to user successful transaction",
        "uid" : "dbfcad1742d7b2f9",
        "parentUid" : "7b44ab22755407c454e439dde15f3ff0",
        "status" : "failed",
        "time" : {
          "start" : 1632557294569,
          "stop" : 1632557294891,
          "duration" : 322
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ "2", "10" ]
      } ],
      "uid" : "7b44ab22755407c454e439dde15f3ff0"
    }, {
      "name" : "Returned error: HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3a7f33760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "a user to user successful transaction",
        "uid" : "41ea7eb86eec07a5",
        "parentUid" : "a5338f119d674f65cd4c8ff7f2496845",
        "status" : "failed",
        "time" : {
          "start" : 1632557294892,
          "stop" : 1632557295206,
          "duration" : 314
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ "9", "10" ]
      } ],
      "uid" : "a5338f119d674f65cd4c8ff7f2496845"
    }, {
      "name" : "Returned error: HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3a74fbaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "a user to user failed transaction",
        "uid" : "a4a691d97c0a7ed",
        "parentUid" : "4ba15a2aa83abc56ed0ed073736d31f5",
        "status" : "failed",
        "time" : {
          "start" : 1632557295207,
          "stop" : 1632557295519,
          "duration" : 312
        },
        "flaky" : true,
        "newFailed" : true,
        "parameters" : [ "10", "10" ]
      } ],
      "uid" : "4ba15a2aa83abc56ed0ed073736d31f5"
    }, {
      "name" : "Returned error: HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3b0c6e5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "a user to user failed transaction",
        "uid" : "75487aa89b639071",
        "parentUid" : "d72fe79b382b624ca7f06a5a506988fc",
        "status" : "failed",
        "time" : {
          "start" : 1632557295520,
          "stop" : 1632557295821,
          "duration" : 301
        },
        "flaky" : true,
        "newFailed" : false,
        "parameters" : [ "11", "10" ]
      } ],
      "uid" : "d72fe79b382b624ca7f06a5a506988fc"
    } ],
    "uid" : "8fb3a91ba5aaf9de24cc8a92edc82b5d"
  }, {
    "name" : "Test defects",
    "children" : [ {
      "name" : "\nYou can implement step definitions for undefined steps with these snippets:\n\n@given(u'there is a contract \\\\'1_Storage.sol\\\\'')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Given there is a contract \\\\'1_Storage.sol\\\\'')\n\n",
      "children" : [ {
        "name" : "simple contract deployment -- @1.1 ",
        "uid" : "9701fef92d83c517",
        "parentUid" : "cc7fccb9825f5452229f5a2a1a916237",
        "status" : "broken",
        "time" : {
          "start" : 1632557333460,
          "stop" : 1632557333461,
          "duration" : 1
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "1_Storage.sol" ]
      } ],
      "uid" : "cc7fccb9825f5452229f5a2a1a916237"
    }, {
      "name" : "\nYou can implement step definitions for undefined steps with these snippets:\n\n@given(u'there is a contract \\\\'3_Ballot.sol\\\\'')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Given there is a contract \\\\'3_Ballot.sol\\\\'')\n\n",
      "children" : [ {
        "name" : "simple contract deployment -- @1.2 ",
        "uid" : "8d3937426fc2c243",
        "parentUid" : "59cb09677238395f3ec1540fdcf9157c",
        "status" : "broken",
        "time" : {
          "start" : 1632557333462,
          "stop" : 1632557333463,
          "duration" : 1
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "3_Ballot.sol" ]
      } ],
      "uid" : "59cb09677238395f3ec1540fdcf9157c"
    }, {
      "name" : "\nYou can implement step definitions for undefined steps with these snippets:\n\n@given(u'there is a contract \\\\'proof.sol\\\\'')\ndef step_impl(context):\n    raise NotImplementedError(u'STEP: Given there is a contract \\\\'proof.sol\\\\'')\n\n",
      "children" : [ {
        "name" : "simple contract deployment -- @1.3 ",
        "uid" : "b71edad36a91f198",
        "parentUid" : "00e7854e067b351b0e008dc2d15826f4",
        "status" : "broken",
        "time" : {
          "start" : 1632557333463,
          "stop" : 1632557333464,
          "duration" : 1
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "proof.sol" ]
      } ],
      "uid" : "00e7854e067b351b0e008dc2d15826f4"
    }, {
      "name" : "ValueError: {'code': -32000, 'message': \"HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3b0d78a30>: Failed to establish a new connection: [Errno 111] Connection refused'))\"}\n",
      "children" : [ {
        "name" : "a user to user successful transaction -- @1.1 ",
        "uid" : "36785ccc2c9ca242",
        "parentUid" : "5d558a9b9230fcbc2426f0ace8df74d6",
        "status" : "broken",
        "time" : {
          "start" : 1632557333467,
          "stop" : 1632557334312,
          "duration" : 845
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "1", "10" ]
      } ],
      "uid" : "5d558a9b9230fcbc2426f0ace8df74d6"
    }, {
      "name" : "ValueError: {'code': -32000, 'message': \"HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3a7394850>: Failed to establish a new connection: [Errno 111] Connection refused'))\"}\n",
      "children" : [ {
        "name" : "a user to user successful transaction -- @1.2 ",
        "uid" : "6fbfbce4b6991140",
        "parentUid" : "af057af32a56b54a3b7d3df9a466508f",
        "status" : "broken",
        "time" : {
          "start" : 1632557334314,
          "stop" : 1632557334615,
          "duration" : 301
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "2", "10" ]
      } ],
      "uid" : "af057af32a56b54a3b7d3df9a466508f"
    }, {
      "name" : "ValueError: {'code': -32000, 'message': \"HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3a748c400>: Failed to establish a new connection: [Errno 111] Connection refused'))\"}\n",
      "children" : [ {
        "name" : "a user to user successful transaction -- @1.3 ",
        "uid" : "666fe872a4a972d",
        "parentUid" : "35d70926bf0a2a841d141d9d518ef74c",
        "status" : "broken",
        "time" : {
          "start" : 1632557334615,
          "stop" : 1632557334917,
          "duration" : 302
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "9", "10" ]
      } ],
      "uid" : "35d70926bf0a2a841d141d9d518ef74c"
    }, {
      "name" : "ValueError: {'code': -32000, 'message': \"HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3a7b2cb80>: Failed to establish a new connection: [Errno 111] Connection refused'))\"}\n",
      "children" : [ {
        "name" : "a user to user failed transaction -- @1.1 ",
        "uid" : "c410c66ba7ef24fc",
        "parentUid" : "a1af5485c8d995825efaf0269ac5461c",
        "status" : "broken",
        "time" : {
          "start" : 1632557334917,
          "stop" : 1632557335218,
          "duration" : 301
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "10", "10" ]
      } ],
      "uid" : "a1af5485c8d995825efaf0269ac5461c"
    }, {
      "name" : "ValueError: {'code': -32000, 'message': \"HTTPConnectionPool(host='18.118.39.244', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3a7f63ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))\"}\n",
      "children" : [ {
        "name" : "a user to user failed transaction -- @1.2 ",
        "uid" : "8a2a394a75679913",
        "parentUid" : "92d1545b267044fcbd4c7dcc9dca0f02",
        "status" : "broken",
        "time" : {
          "start" : 1632557335218,
          "stop" : 1632557335521,
          "duration" : 303
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "11", "10" ]
      } ],
      "uid" : "92d1545b267044fcbd4c7dcc9dca0f02"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ],
  "name" : "categories"
}